### ISSUE TITLE
embed img thumbnail on click bar div

### ISSUE THREAD

**Issue by cparello** [emilpalsson/react-tiny-accordion#2]
There does not seem to be an easy way to include a img so a thumnail appears on the bar you click like you do the data-header to get the title to appear on the rendered div...

Am I missing something?

**Comment by emilpalsson** [comment]
Sorry for the very late response. However, the data-header prop doesn't necessarily need to be a string literal, but can be any React component. This is perfectly valid:

    <Accordion className="accordion">
      <div data-header={<img src="..." height={24} />}>
        Content
      </div>
    </Accordion>

See working example here: https://codesandbox.io/s/31w132m88q

I guess it would be a good idea to add this to the docs, so I leave the issue open until I've done that (or if anyone wants to make a PR).

**Comment by emilpalsson** [comment]
Added to readme, closing.
